<?xml version="1.0" encoding="utf-8"?><Database Name="ActivityManager" Class="ActivityManagerDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Table Name="dbo.Administration" Member="Administration">
    <Type Name="Administration">
      <Column Name="adminID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="adminPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Organization" Member="Organization">
    <Type Name="Organization">
      <Column Name="organizationID" Type="System.String" DbType="Char(13) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="organizationName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="organizationPassword" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Association Name="Organization_Activity" Member="Activity" ThisKey="organizationID" OtherKey="activityOrgID" Type="Activity" />
    </Type>
  </Table>
  <Table Name="dbo.Student" Member="Student">
    <Type Name="Student">
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID" Type="System.String" DbType="Char(18)" CanBeNull="true" />
      <Column Name="studentName" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Association Name="Student_StudentIdentified" Member="StudentIdentified" ThisKey="studentID" OtherKey="studentID" Type="StudentIdentified" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="dbo.StudentIdentified" Member="StudentIdentified">
    <Type Name="StudentIdentified">
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="phone" Type="System.String" DbType="Char(11) NOT NULL" CanBeNull="false" />
      <Column Name="studentName" Type="System.String" DbType="VarChar(22) NOT NULL" CanBeNull="false" />
      <Column Name="gender" Type="System.String" DbType="Char(2) NOT NULL" CanBeNull="false" />
      <Column Name="faculty" Type="System.String" DbType="VarChar(26) NOT NULL" CanBeNull="false" />
      <Column Name="major" Type="System.String" DbType="VarChar(26) NOT NULL" CanBeNull="false" />
      <Column Name="class" Type="System.String" DbType="VarChar(10) NOT NULL" CanBeNull="false" />
      <Column Name="credit_1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="credit_2" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="credit_3" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="studentPassword" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Association Name="StudentIdentified_LikedActivity" Member="LikedActivity" ThisKey="studentID" OtherKey="studentID" Type="LikedActivity" />
      <Association Name="StudentIdentified_SignedActivity" Member="SignedActivity" ThisKey="studentID" OtherKey="studentID" Type="SignedActivity" />
      <Association Name="StudentIdentified_ActivityAppraise" Member="ActivityAppraise" ThisKey="studentID" OtherKey="studentID" Type="ActivityAppraise" />
      <Association Name="StudentIdentified_ActivitySignTeam" Member="ActivitySignTeam" ThisKey="studentID" OtherKey="studentID" Type="ActivitySignTeam" />
      <Association Name="Student_StudentIdentified" Member="Student" ThisKey="studentID" OtherKey="studentID" Type="Student" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Place" Member="Place">
    <Type Name="Place">
      <Column Name="placeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="placeName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="placeState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Place_Activity" Member="Activity" ThisKey="placeID" OtherKey="activityPlaceID" Type="Activity" />
    </Type>
  </Table>
  <Table Name="dbo.LikedActivity" Member="LikedActivity">
    <Type Name="LikedActivity">
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="StudentIdentified_LikedActivity" Member="StudentIdentified" ThisKey="studentID" OtherKey="studentID" Type="StudentIdentified" IsForeignKey="true" />
      <Association Name="Activity_LikedActivity" Member="Activity" ThisKey="activityID" OtherKey="activityID" Type="Activity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.SignedActivity" Member="SignedActivity">
    <Type Name="SignedActivity">
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="checkIn" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="checkOut" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="StudentIdentified_SignedActivity" Member="StudentIdentified" ThisKey="studentID" OtherKey="studentID" Type="StudentIdentified" IsForeignKey="true" />
      <Association Name="Activity_SignedActivity" Member="Activity" ThisKey="activityID" OtherKey="activityID" Type="Activity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Activity" Member="Activity">
    <Type Name="Activity">
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityName" Type="System.String" DbType="VarChar(30) NOT NULL" CanBeNull="false" />
      <Column Name="activityIntro" Type="System.String" DbType="VarChar(400) NOT NULL" CanBeNull="false" />
      <Column Name="activityPlaceID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="activityOrgID" Type="System.String" DbType="Char(13) NOT NULL" CanBeNull="false" />
      <Column Name="availableCredit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxSigned" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="signed" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="activityState" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="signStartDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="signEndDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="holdDate" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="holdStart" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="holdEnd" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="submitTime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="failReason" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="activityType" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Activity_LikedActivity" Member="LikedActivity" ThisKey="activityID" OtherKey="activityID" Type="LikedActivity" />
      <Association Name="Activity_SignedActivity" Member="SignedActivity" ThisKey="activityID" OtherKey="activityID" Type="SignedActivity" />
      <Association Name="Activity_ActivityEnableTeam" Member="ActivityEnableTeam" ThisKey="activityID" OtherKey="activityID" Type="ActivityEnableTeam" Cardinality="One" />
      <Association Name="Activity_ActivityCheckCode" Member="ActivityCheckCode" ThisKey="activityID" OtherKey="activityID" Type="ActivityCheckCode" Cardinality="One" />
      <Association Name="Activity_ActivityAppraise" Member="ActivityAppraise" ThisKey="activityID" OtherKey="activityID" Type="ActivityAppraise" />
      <Association Name="Organization_Activity" Member="Organization" ThisKey="activityOrgID" OtherKey="organizationID" Type="Organization" IsForeignKey="true" />
      <Association Name="Place_Activity" Member="Place" ThisKey="activityPlaceID" OtherKey="placeID" Type="Place" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityEnableTeam" Member="ActivityEnableTeam">
    <Type Name="ActivityEnableTeam">
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="minVolume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="maxVolume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ActivityEnableTeam_ActivitySignTeam" Member="ActivitySignTeam" ThisKey="activityID" OtherKey="activityID" Type="ActivitySignTeam" />
      <Association Name="Activity_ActivityEnableTeam" Member="Activity" ThisKey="activityID" OtherKey="activityID" Type="Activity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityCheckCode" Member="ActivityCheckCode">
    <Type Name="ActivityCheckCode">
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="checkInCode" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Column Name="checkOutCode" Type="System.String" DbType="Char(6)" CanBeNull="true" />
      <Association Name="Activity_ActivityCheckCode" Member="Activity" ThisKey="activityID" OtherKey="activityID" Type="Activity" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivityAppraise" Member="ActivityAppraise">
    <Type Name="ActivityAppraise">
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="credit" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="appraise" Type="System.String" DbType="VarChar(200)" CanBeNull="true" />
      <Association Name="Activity_ActivityAppraise" Member="Activity" ThisKey="activityID" OtherKey="activityID" Type="Activity" IsForeignKey="true" />
      <Association Name="StudentIdentified_ActivityAppraise" Member="StudentIdentified" ThisKey="studentID" OtherKey="studentID" Type="StudentIdentified" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ActivitySignTeam" Member="ActivitySignTeam">
    <Type Name="ActivitySignTeam">
      <Column Name="teamID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="activityID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="teamName" Type="System.String" DbType="VarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="studentID" Type="System.String" DbType="Char(10) NOT NULL" CanBeNull="false" />
      <Column Name="captain" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="audit" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="member" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="volume" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="ActivityEnableTeam_ActivitySignTeam" Member="ActivityEnableTeam" ThisKey="activityID" OtherKey="activityID" Type="ActivityEnableTeam" IsForeignKey="true" />
      <Association Name="StudentIdentified_ActivitySignTeam" Member="StudentIdentified" ThisKey="studentID" OtherKey="studentID" Type="StudentIdentified" IsForeignKey="true" />
    </Type>
  </Table>
</Database>